<?php
// Generated by Zend Framework 2
return array(
    'GBase\Module'              => __DIR__ . '//Module.php',
    'GBase\Mapper\BaseDbMapper' => __DIR__ . '//src/GBase/Mapper/BaseDbMapper.php',
);